name = "themecanary"
main = "worker.js"
compatibility_date = "2024-01-01"

rules = [
  { type = "Text", globs = ["**/*.sh"], fallthrough = true }
]

routes = [
  { pattern = "theme.olsite.dev/*", zone_name = "olsite.dev" }
]
